Zbear/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # "include" sends the remaining string to the included URLconf
    # it is using for reference other URLconf
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /polls/
    # url(r'^$', views.index, name='index'),

    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^$(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/
    # ^ is start line
    # $ is end line
    # (?P<question_id>regex) this is named capturing , capture value into question_id by regex
    # this regex capture any number 0-9 with more than one letters

    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    #
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote')
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.


class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # problem with datetime.timedelta does not returns actual local time value
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):

    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

# timezone.localtime(timezone.now())

questionProcessing/models.py
from django.db import models

# Create your models here.


class TrainingSet(models.Model):

    question = models.CharField(max_length=200)
    answer_type = models.CharField(max_length=50)

    def __unicode__(self):
        return self.question

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Question,Choice
from django.views import generic
from django.utils import timezone
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list' #what is context_object_name

    def get_queryset(self):
        """
        :return: The last five published questions(not including those set to be published in the future)
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        excludes any questions that aren't published yet
        :return:
        """
        return Question.objects.filter(pub_date__lte= timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',{
            'question' : p,
            'error_message' : "you didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

questionProcessing/views.py
from django.shortcuts import render
from .models import TrainingSet
from django.views import generic
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'questionProcessing/index.html'
    model = TrainingSet

polls/templates/polls/detail.html
<h1> {{ question.question_text }}</h1>

{% if error_message %}
    <p>
        <strong>{{ error_message }}</strong>
    </p>
{% endif %}
<form action="{% url 'polls:vote' question.id%}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }} </label>
        <br/>
    {% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
{#            The way this works is by looking up the URL definition as specified #}
{#            in the polls.urls module. You can see exactly where the URL name of ‘detail’#}
        <a href="{% url 'polls:detail' question.id %}"> {{ question.question_text }}</a>
        </li>
    {% endfor %}
    </ul>
    {% else %}
    <p> No polls are available.</p>
{% endif %}

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}"> Vote again?</a>